---
ci:
  autoupdate_schedule: monthly
  skip: [pip-audit]

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: 'tests/'
        args: [--omit-covered-files, --fail-under=90]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [lxml]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      -   id: pip-audit
          args: [--local]

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [--pytest-test-first]
