dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install -U pip setuptools
  - pip install -U coveralls pycodestyle pydocstyle pytest-mccabe pytest-random pylint
before_script:
  - pip install -Ur requirements.txt
  - python3 -V
script:
  - python3 -m pytest --mccabe -v pyerge
  - coverage run --source=pyerge -m pytest -v --random
  - pycodestyle --statistics --count pyerge
  - pydocstyle --count pyerge
#  - pylint pyerge
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_OS_NAME == "linux" ]]; then coveralls; fi
