CFLAGS="-march=native -O2 -pipe"
CXXFLAGS="${CFLAGS}"
MAKEOPTS="-j16"
FEATURES="sandbox -usersandbox -userpriv -pid-sandbox -ipc-sandbox -network-sandbox -strict userfetch parallel-fetch"
ACCEPT_KEYWORDS="~amd64"
GENTOO_MIRRORS="http://tux.rainside.sk/gentoo/ ftp://tux.rainside.sk/gentoo/"
