name: Tests

on: workflow_call

jobs:
  unit_test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install uv and set the Python"
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          activate-environment: true

      - name: "Install the project and test dependencies"
        run: uv sync

      - name: "Test with pytest"
        run: |
          python -m pytest -v

      - name: "Upload test results"
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            tests/resources/*
          retention-days: 5

      - name: "Check pip-audit"
        run: |
          pip-audit -lv --progress-spinner off --ignore-vuln PYSEC-2022-42969
